### ISSUE TITLE
Can't get it to work. Please help :)

### ISSUE THREAD

**Issue by lifer0se** [mdgaziur/findex#4]
Hey! Running findex on terminal does nothing for me. The process keeps on running, no errors are diplayed, no windows pop up. I tried bare and ls | findex. (I've copied style.css to .config/findex)

I'd like to check it out and see what this is about. I'm using arch + xmonad. What am I missing?

**Comment by yochananmarqos** [comment]
This is the output I received built from the latest commit:

```
❯ findex
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/query.rs:148:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
RUST_BACKTRACE=full findex
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/query.rs:148:41
stack backtrace:
   0:     0x55c97cd498f5 - <unknown>
   1:     0x55c97ccd3c5c - <unknown>
   2:     0x55c97cd48e74 - <unknown>
   3:     0x55c97cd48c5f - <unknown>
   4:     0x55c97cd68dc6 - <unknown>
   5:     0x55c97cd68d66 - <unknown>
   6:     0x55c97cd68d22 - <unknown>
   7:     0x55c97cca7560 - <unknown>
   8:     0x55c97cca76bc - <unknown>
   9:     0x55c97ccb1fb6 - <unknown>
  10:     0x55c97ccae9d7 - <unknown>
  11:     0x55c97ccbc9da - <unknown>
  12:     0x55c97ccba45e - <unknown>
  13:     0x7f3d67c38d8f - g_closure_invoke
  14:     0x7f3d67c54718 - <unknown>
  15:     0x7f3d67c55dd9 - g_signal_emit_valist
  16:     0x7f3d67c56330 - g_signal_emit
  17:     0x7f3d670bf739 - <unknown>
  18:     0x7f3d670ca28a - g_application_run
  19:     0x55c97ccc2825 - <unknown>
  20:     0x55c97ccc0c93 - <unknown>
  21:     0x55c97ccc146c - <unknown>
  22:     0x7f3d66cd3b25 - __libc_start_main
  23:     0x55c97ccabf6e - <unknown>
  24:                0x0 - <unknown>
```

**Comment by mdgaziur** [comment]
Can you share more detailed information?
Which AUR package did you use?

**Comment by mdgaziur** [comment]
Closing due to lack of response
